name: DeviceFarm Report

on:
  workflow_dispatch:
  push:

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Crear carpeta de reportes
      run: mkdir -p reports

    - name: Copiar archivo de Device Farm
      run: cp "device-farm-output.txt" reports/devicefarm-log.txt

    - name: Instalar dependencias
      run: npm install

    - name: Generar reporte HTML
      run: |
        node scripts/generate-report.js \
          reports/devicefarm-log.txt \
          reports/devicefarm-report.html

        - name: Subir artefacto del reporte
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: devicefarm-report
        path: reports/devicefarm-report.html

    - name: Enviar link del reporte a Slack
      uses: slackapi/slack-github-action@v1.27.0
      with:
        payload: |
          {
            "channel": "#prueba-app",
            "text": "ðŸ“„ *Nuevo Reporte de Device Farm*\nðŸ‘‰ <${{ steps.upload.outputs.artifact-url }}|Click acÃ¡ para ver el reporte HTML>"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
