name: DeviceFarm Report

on:
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Crear carpeta de reportes
        run: mkdir -p reports

      - name: Copiar archivo de Device Farm
        run: cp device-farm-output.txt reports/devicefarm-log.txt

      - name: Instalar dependencias
        run: npm install

      - name: Generar reporte HTML
        run: |
          node scripts/generate-report.js \
            reports/devicefarm-log.txt \
            reports/devicefarm-report.html

      - name: Subir artefacto del reporte
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: devicefarm-report
          path: reports/devicefarm-report.html

      - name: Guardar variables para Slack
        id: vars
        run: |
          echo "text=${{ steps.generate-report.outputs.SLACK_TEXT }}" >> $GITHUB_OUTPUT
          echo "dur=${{ steps.generate-report.outputs.DURATION }}" >> $GITHUB_OUTPUT
          echo "files=${{ steps.generate-report.outputs.FILECOUNT }}" >> $GITHUB_OUTPUT

      - name: Enviar link del reporte a Slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "channel": "#prueba-app",
              "text": "*${{ steps.vars.outputs.text }}*\n\nğŸ“± Dispositivo: Android\nâ±ï¸ DuraciÃ³n total: ${{ steps.vars.outputs.dur }}\nğŸ“ Archivos ejecutados: ${{ steps.vars.outputs.files }}\nğŸ‘‰ <${{ steps.upload.outputs.artifact-url }}|*Ver reporte completo*>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

